### ISSUE TITLE
What is `OPT_NONEG` doing?

### ISSUE THREAD

**Issue by CMCDragonkai** [cofyc/argparse#11]
And what are the flags for `argparse_init`? The example only shows `0`.

**Comment by cofyc** [comment]
hi,

`OPT_BOOLEAN` and `OPT_BIT` types support negation, you can use `no-` prefix to negate the value, for example:

```
OPT_BIT(0, "read", &perms, "read perm", NULL, PERM_READ, OPT_NONEG),
OPT_BIT(0, "write", &perms, "write perm", NULL, PERM_WRITE),
OPT_BIT(0, "exec", &perms, "exec perm", NULL, PERM_EXEC),
```

`--write` turns on write permission, `--no-exec` means no exec permission.

But, if you don't want this feature, you can use `OPT_NONEG` flag to turn off this feature. In the example above, `--no-write` and `--no-exec` is valid, but `--no-read` is invalid.

**Comment by CMCDragonkai** [comment]
Can those flags be put into `argparse_init(&argparse, options, usage, 0);`. See the `0` at the end?

**Comment by cofyc** [comment]
@CMCDragonkai 

NO, `OPT_NONEG` is per `OPT` flag.
