### ISSUE TITLE
need for char** array type and function callbacks

### ISSUE THREAD

**Issue by FraMecca** [cofyc/argparse#12]
Hi Cofyc. Some time ago I forked argparse for a personal need. 
I added the capability to call a function associated with an argument and a new type ARGPARSE_OPT_ARRAY that works and allocate char ** .

My fork can be found here:
https://github.com/FraMecca/libargparse

and this is the fork in action:
http://francescomecca.eu:3000/pesceWanda/kpd/src/development/src/main.c

If you want and if it is needed, we can work to merge my code to your original work

Let me know if interested.

Francesco

**Comment by cofyc** [comment]
hi, @FraMecca 

I don't want `argparse` to do any `malloc/free` stuffs, sorry.
