### ISSUE TITLE
subcommands

### ISSUE THREAD

**Issue by aep** [cofyc/argparse#30]
thanks for making a malloc-free arg parser that has a sane api.
any chance we could add subcommands? 

    thething subcommand -xyz

**Comment by cofyc** [comment]
you need to implement this by yourself and it should not be hard. Take the first argument as the name of the sub-command and pass the rest arguments to it. in each sub-command, you can use `argparse` to parse the arguments.

**Comment by aep** [comment]
yep doing that now. its not as good as what i'm porting from (rust's clap) but i understand adding this to argparse is a bit too much. 

thanks
