### ISSUE TITLE
Version management

### ISSUE THREAD

**Issue by M3TIOR** [cofyc/argparse#52]
I'm planning on using this project in my *GNU Moreutils `vipe`* rewrite, I was curious what version management system this project uses. You have some git tags that seem to be Semantic Versioned but there have been quite a few bug fixes since then and no tagged version patches.

**Comment by cofyc** [comment]
yes, it's semantic versioned
the core API is table but a new flag `ARGPARSE_IGNORE_UNKNOWN_ARGS` is introduced, `v1.1.0` is tagged and pushed, you can use this version.

**Comment by M3TIOR** [comment]
Thanks
