### ISSUE TITLE
Make release tag

### ISSUE THREAD

**Issue by msikma** [Cofyc/argparse#8]
I'm doing some C code experiments using this very nice argparse implementation. I wrote a small script that clones repositories so that it's easy to install third party code such as this. For that reason it'd be preferable for me if there was a tag. (Since you can clone tags/branches directly, something you can't do for commit hashes.) Right now it seems the code works quite fine, so maybe a 1.0.0 release is in order?

**Comment by aburgh** [comment]
Is the following an option for you? It will download a snapshot of the specified commit:
```
$ curl -o argparse.tar.gz --location https://github.com/cofyc/argparse/archive/e1277bf1e3f47663fad54f84ca723db7688630d4.tar.gz 
```
In this example, the commit is the latest commit in this project, but you can specify older commits so you can always reproduce a specific build. You can change the extension to get different archive formats, like bz2 or zip.

**Comment by Cofyc** [comment]
Hi,

Thank you for reminding this. This library is stable enough, [1.0.0](https://github.com/Cofyc/argparse/releases/tag/v1.0.0) is released now!

**Comment by msikma** [comment]
Thanks so much! Also to @aburgh for the alternate suggestion. :+1:
