### ISSUE TITLE
null pointer assignment to argv

### ISSUE THREAD

**Issue by kkirby** [cofyc/argparse#9]
When you assign `this->output` to `argv`, and then later on assign a `null` value to `this->output[x]`, it also updates `argv` to have a null pointer. This is unexpected and `argv` shouldn't be modified.

**Comment by Cofyc** [comment]
Hi, 

At beginning, I wrote this library to simplify arguments parsing as possible as I can. Modifying original `argv` may have side effects (See issue #3). 

It's hard to change the design now. To work around it, you can make a copy at first, then pass the copy of `argv` to `argparse_parse`.
